# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]
  push:
    branches:
      - master    

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip wheel
        pip install setuptools twine
    - name: Run tests
      env:
        CODECOV_TOKEN: "26b7e6e5-a352-4ddf-bc3b-023387c19564"
      run: |
        pip install pytest
        pip install pytest-cov
        pip install codecov
        cd test
        pytest --cov=../EventNotifier --cov-report=html
        codecov -t "26b7e6e5-a352-4ddf-bc3b-023387c19564"
        cd ..
    - name: Upload single file
      run: echo "Hello World" > file.txt
      with:
        name: file
        path: file.txt
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        CODECOV_TOKEN: "26b7e6e5-a352-4ddf-bc3b-023387c19564"
      run: |
        python ./pypi/setup.py sdist bdist_wheel
        twine upload dist/*



